config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  root to: "home#index"
  patch '/capture', to: 'pokemons#capture'
  patch '/damage', to: 'pokemons#damage'
  patch '/heal', to: 'pokemons#heal'
  patch '/trainers/:id', to: 'trainers#choose'
  get '/new', to: 'pokemons#new'
  post '/trainers/:id', to: 'pokemons#create'
  resources :trainers
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	belongs_to :trainer, optional: true
	validates :name, presence: true, uniqueness: true
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pokemons, dependent: :destroy
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

	def capture
		@pokemon = Pokemon.find(params[:id])
		@pokemon.trainer = current_trainer
		@pokemon.save
		redirect_to :controller => 'home', :action => 'index'
	end

	def damage
		@pokemon = Pokemon.find(params[:id])
		#need to target other pokemon and decrement its' health
		@pokemon.health -= 10 
		@pokemon.save
		redirect_to trainer_path(@pokemon.trainer.id)
	end

	def heal
		@pokemon = Pokemon.find(params[:id])
		@pokemon.health += 10 
		@pokemon.save
		redirect_to trainer_path(@pokemon.trainer.id)
	end

	def create
		@pokemon = Pokemon.create(new_params)#what happens to pokemon.new in show?
		@pokemon.trainer = current_trainer
		@pokemon.level = 1
		@pokemon.health = 100
		if @pokemon.save
			redirect_to trainer_path(current_trainer.id) #why do i need this if simpleformfor has he redirect url?
		else 
			flash[:error] = @pokemon.errors.full_messages.to_sentence
		end
	end

	def new
		@pokemon = Pokemon.new
	end
	

	# def show 
	# 	@pokemon = Pokemon.new  #why do I need this? what does it have to do with @pokemon in simpleformfor
	# 	render :new
	# end


	private

	def new_params
		params.require(:pokemon).permit(:name, :ndex)
	end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <% if @pokemon.ndex %>
    <%= image_tag("pokemon/#{@pokemon.ndex}.png", alt: "pokemon") %>
  <% end %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
<% end %>

<%= image_tag("pokemon/pokemon-family.jpg", :alt => "pokemon") %>

app/views/pokemons/new.html.erb
<%= simple_form_for @pokemon, url: trainer_path(current_trainer.id) do |f| %>
  <%= f.input :name %>
  <%= f.collection_radio_buttons(
    :ndex, (1..649).map {|ndex| [ndex, ndex]}, :first, :last
  ) do |b| %>
  <div class="pokemon-choice-container">
    <%= b.label { image_tag("pokemon/#{b.text}.png") + b.radio_button } %>
  </div>
<% end %>
  <%= f.button :submit, class: "create-pokemon-btn" %>
<% end %>

app/views/trainers/choose.html.erb
<div class="dropdown">
  <button onclick="myFunction()" class="dropbtn">Dropdown</button>
  <div id="myDropdown" class="dropdown-content">
  	<%= @pokemons.each do |pokemon| %>
    	<%= button_to "#{pokemon.name}", damage_path(id: pokemon), :class => "button medium", :method => :patch %>
    <% end %>
  </div>
</div>

app/views/trainers/show.html.erb
<%= stylesheet_link_tag "dropdown" %>
<%= javascript_include_tag "dropdown" %>
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>
<% if current_trainer.id == @trainer.id %>
  <%= button_to "Make a new pokeMANZ", new_path(@trainer), :class => "button medium", :method => :get  %>
<% end %>


<% @trainer.pokemons.each do |pokemon| %>
<br>
<% if pokemon.ndex and @trainer.id == current_trainer.id %>
    <%= image_tag("pokemon/#{pokemon.ndex}.png", alt: "pokemon") %>
    <p> Name: <%= pokemon.name %> </p>
    <p> Level: <%= pokemon.level %> </p>
    <p> Health:<%= pokemon.health %> </p>
    <div class="dropdown">
  <button onclick="myFunction(this)" class="dropbtn">Damage!</button>
  <div id="myDropdown" class="dropdown-content">
    <% @trainer.pokemons.each do |pokemon| %>
        <%= button_to "#{pokemon.name}", damage_path(id: pokemon), :class => "button small", :method => :patch %>
        <% end %>
  </div>
</div>
<br />
    <%= button_to "Heal!", heal_path(id: pokemon), :class => "button medium", :method => :patch %>
    
<% elsif pokemon.ndex and pokemon.health > 0 %>
    <%= image_tag("pokemon/#{pokemon.ndex}.png", alt: "pokemon") %>
    <p> Name: <%= pokemon.name %> </p>
    <p> Level: <%= pokemon.level %> </p>
    <p> Health:<%= pokemon.health %> </p>
     <div class="dropdown">
  <button onclick="myFunction(this)" class="dropbtn">Damage!</button>
  <div id="myDropdown" class="dropdown-content">
    <% @trainer.pokemons.each do |pokemon| %>
            <% if pokemon.ndex and pokemon.health > 0 %>
        <%= button_to "#{pokemon.name}", damage_path(id: pokemon), :class => "button small", :method => :patch %>
            <% end %>
        <% end %>

  </div>
</div>
<% end %>
<% end %>